name: tensorflow_beginner
channels:
  - conda-forge
dependencies:
  - ipykernel
  - matplotlib
  - openpyxl
  - nodejs
  - numpy
  - pandas
  - pip
  - seaborn
  - scikit-learn
  - tensorflow-gpu=2.1.0
  - tensorboard=2.2.1              
  - tensorboard-plugin-wit=1.6.0           
  - tensorflow-estimator=2.1.0    
  - python=3.7.0
  - typing
  - tqdm
  - pip:
      - glob3
      - pickle-mixin
      - pyparsing # to fix matplotlib import